2020-06-30 14:55:39 autoreload.py[line:217] INFO /Users/vcrting/Downloads/SMSTask/Twilio/Appis/Web/task/aps.py changed, reloading.
2020-06-30 14:57:55 autoreload.py[line:217] INFO /Users/vcrting/Downloads/SMSTask/Twilio/Appis/Web/task/aps.py changed, reloading.
2020-06-30 14:59:03 log.py[line:228] ERROR Internal Server Error: /task_running/
Traceback (most recent call last):
  File "/Users/vcrting/Downloads/SMSTask/Twilio/Appis/Web/task/aps.py", line 41, in aps
    scheduler.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/schedulers/background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 162, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 867, in _real_add_job
    store.add_job(job)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 29, in inner
    return func(*a, **k)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django_apscheduler/jobstores.py", line 95, in add_job
    job_state=pickle.dumps(job.__getstate__(), self.pickle_protocol)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/job.py", line 241, in __getstate__
    'instead.' % (self.func,))
ValueError: This Job cannot be serialized since the reference to its callable (<function aps.<locals>.job at 0x106ddb510>) could not be determined. Consider giving a textual reference (module:function name) instead.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/vcrting/Downloads/SMSTask/Twilio/Appis/Web/views.py", line 290, in get
    aps()
  File "/Users/vcrting/Downloads/SMSTask/Twilio/Appis/Web/task/aps.py", line 46, in aps
    scheduler.shutdown()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/schedulers/background.py", line 39, in shutdown
    super(BackgroundScheduler, self).shutdown(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/schedulers/blocking.py", line 22, in shutdown
    super(BlockingScheduler, self).shutdown(wait)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 184, in shutdown
    raise SchedulerNotRunningError
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running
2020-06-30 14:59:03 log.py[line:228] WARNING Not Found: /favicon.ico
2020-06-30 15:02:18 autoreload.py[line:217] INFO /Users/vcrting/Downloads/SMSTask/Twilio/Appis/Web/task/aps.py changed, reloading.
